name: wheels

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-14, macos-15-intel, windows-latest ]
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.14" # https://cibuildwheel.pypa.io/en/stable/cpp_standards/#macos-and-deployment-target-versions

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4
        with:
          package-dir: ./
          output-dir: ./wheelhouse

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  check_contents:
    name: Build full dist and check contents
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - uses: actions/upload-artifact/merge@v4
        with:
          name: "wheels"
          pattern: "wheels-*"
          delete-merged: true

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Build sdist
        run: |
          pip install build click
          python -m build --sdist

      - name: Test packages
        run: |
          python test_contents.py

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: pkgs
          path: ./dist

  test:
    name: Test on ${{ matrix.os }}
    needs: check_contents
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-14, macos-15-intel, windows-latest ]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      # https://github.com/wlav/cppyy/issues/308
      - name: Configure MacOS
        if: runner.os == 'macOS'
        run: |
          # brew install zstd # already installed
          echo "LD_LIBRARY_PATH=/opt/homebrew/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

      # https://github.com/wlav/cppyy/issues/282
      - name: Configure Windows
        if: runner.os == 'Windows'
        run: |
          pip install setuptools --force-reinstall
          pip install cppyy-cling==6.32.8 --no-deps --no-build-isolation --force-reinstall
          pip install cppyy-backend==1.15.3 --no-deps --no-build-isolation --force-reinstall
          pip install CPyCppyy==1.13.0 --no-deps --no-build-isolation --force-reinstall
          pip install cppyy==3.5.0 --no-deps --no-build-isolation --force-reinstall

      - name: Install wheel
        run: pip install --no-index --find-links ./dist ogdf-wheel

      - name: List installed files from wheel
        run: pip show -f ogdf-wheel

      - name: Install ogdf-python
        run: pip install git+https://github.com/N-Coder/ogdf-python.git

      - name: Get ogdf-python release info
        run: python -m ogdf_python
        env:
          OGDF_PYTHON_MODE: release

      - name: Get ogdf-python debug info
        run: python -m ogdf_python
        env:
          OGDF_PYTHON_MODE: debug

      - name: Test ogdf-python layouts in release mode
        run: python test_layouts.py
        env:
          OGDF_PYTHON_MODE: release

      - name: Test ogdf-python layouts in debug mode
        run: python test_layouts.py
        env:
          OGDF_PYTHON_MODE: debug

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: svgs-${{ matrix.os }}
          path: ./*.svg
